hood/urls.py
from django.urls import path
from . import views
from .views import (HomePage,
                    ProfilePage,
                    CreateNewPost,
                    SinglePost,
                    CreateBusiness,
                    UpdateProfile,
                    BusinessPage)
from django.conf import settings
from django.conf.urls.static import static

app_name = 'hood'

urlpatterns = [
                  path('', HomePage.as_view(), name='home'),
                  path('profile/', ProfilePage.as_view(), name='profile'),
                  path('update/<int:pk>/', UpdateProfile.as_view(), name='update_profile'),
                  path('post/new', CreateNewPost.as_view(), name='new_post'),
                  path('post/<int:pk>/', SinglePost.as_view(), name='post-detail'),
                  path('business/new', CreateBusiness.as_view(), name='new_business'),
                  path('business/',BusinessPage.as_view(), name='business')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myhood/urls.py
# from django.conf.urls import url,include
from django.urls import path, include
from django.contrib import admin
# from users.views import SignUpView
from users import views as user_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', user_view.register, name='registration'),
    path('', include('hood.urls')),
]

hood/models.py
# -*- coding: utf-8 -*-
# from __future__ import unicode_literals

from django.db import models
from django.db import models
import datetime as dt
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import post_save
from PIL import Image


# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField()
    hood_name = models.CharField(max_length=30)
    profile_pic = models.ImageField(upload_to='photos/', default='kent.jpg')
    phone_number = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.profile_pic.path)
        if img.height > 250 or img.width > 180:
            output_size = (220, 150)
            img.thumbnail(output_size)
            img.save(self.profile_pic.path)

    def get_absolute_url(self):
        return reverse('hood:update_profile', kwargs={'pk': self.pk})

    def create_profile(sender, **kwargs):
        if kwargs['created']:
            profile = Profile.objects.create(user=kwargs['instance'])

    post_save.connect(create_profile, sender=User)

    def __str__(self):
        return f'{self.user.username} Profile'


class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    picture = models.ImageField(upload_to='photos/', default='post.jpg')
    pub_date = models.DateTimeField(auto_now_add=True)
    profile = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse('hood:home')


class Neighborhood(models.Model):
    name = models.CharField(max_length=30)
    location = models.CharField(max_length=30)
    rent_rates = models.IntegerField(default=0)
    description = models.CharField(max_length=30)
    closest_health_contact = models.IntegerField(default=0)
    closest_security_contact = models.IntegerField(default=0)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Business(models.Model):
    name = models.CharField(max_length=30)
    business_pic = models.ImageField(upload_to='photos/', default='biz.jpg')
    description = models.TextField()
    profile = models.ForeignKey(User, on_delete=models.CASCADE)
    neighborhood = models.ForeignKey(Neighborhood, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.description

    def get_absolute_url(self):
        return reverse('hood:business')

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

hood/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.views.generic import ListView, DetailView
from .models import Profile, Post, Business, Neighborhood
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin


# def home(request):
#
#     return render(request, 'home.html')

class HomePage(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'home.html'
    ordering = ['-pub_date']
    login_url = 'login'


class ProfilePage(LoginRequiredMixin, TemplateView):
    template_name = 'profile.html'
    login_url = 'login'


class CreateNewPost(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'new_post.html'
    fields = ['title', 'content', 'picture']
    login_url = 'login'

    def form_valid(self, form):
        form.instance.profile = self.request.user
        form.instance.neighborhood = self.request.user
        return super().form_valid(form)


class CreateBusiness(LoginRequiredMixin, CreateView):
    model = Business
    template_name = 'new_business.html'
    fields = ['name', 'description','business_pic']
    login_url = 'login'

    def form_valid(self, form):
        form.instance.profile = self.request.user
        return super().form_valid(form)


class SinglePost(LoginRequiredMixin, DetailView):
    model = Post
    template_name = 'post-detail.html'
    login_url = 'login'


class UpdateProfile(UpdateView):
    model = Profile
    template_name = 'update_profile.html'


class BusinessPage(LoginRequiredMixin, ListView):
    model = Business
    template_name = 'business.html'
    login_url = 'login'

users/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages
from .forms import UserRegistrationForm


# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('login')
    else:
        form = UserRegistrationForm()
    return render(request, 'registration.html', {"form": form})

# class SignUpView(generic.CreateView):
#     form_class = UserCreationForm
#     success_url = reverse_lazy('login')
#     template_name = 'registration.html'

hood/templates/base.html
{%load bootstrap4%}
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     {% if title %}
  <title>The Hood - {{title}}</title>
  {% else %}
    <title> The Hood </title>
  {% endif %}

    {% block styles%}
    {%bootstrap_css%}
      <!-- Font Awesome -->
  <link href="https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Press+Start+2P&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Google Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.12.0/css/mdb.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.9/css/mdb.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% endblock%}
</head>

<body>


{% include 'navbar.html' %}
{% block content %}

{%endblock%}
{%include 'footer.html'%}
<!--scripts-->
{%block scripts %}
<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.12.0/js/mdb.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% bootstrap_javascript%}
{%endblock%}

</body>
</html>

hood/templates/business.html
{%extends 'base.html'%}
{%block content%}
<div class="container-fluid">
    
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 mt-3">
            <div class="jumbotron">
        
                <h2 class="display-4 text-center">Businesses</h2>
            </div>
        </div>
        <div class="col-md-2 mt-3"> <a class="btn btn-info" href="{%url 'hood:new_business'%}">Create Business</a></div>
    </div>
      {% for business in object_list%}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            
            <!-- News jumbotron -->
<div class="jumbotron text-center hoverable p-4 mt-5">

    <!-- Grid row -->
    <div class="row">
  
      <!-- Grid column -->
      <div class="col-md-4 offset-md-1 mx-3 my-3">
  
        <!-- Featured image -->
        <div class="view overlay">
          <img src="{{business.business_pic.url}}">
          <a>
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>
  
      </div>
      <!-- Grid column -->
  
      <!-- Grid column -->
      <div class="col-md-7 text-md-left ml-3 mt-3">
  
        <!-- Excerpt -->
        <a href="#!" class="green-text">
          <h6 class="h6 pb-1"><i class="fas fa-desktop pr-1"></i> Work</h6>
        </a>
  
        <h4 class="h4 mb-4">{{business.name}}</h4>
  
        <p class="font-weight-normal">{{business.description}}.</p>
        <p class="font-weight-normal">by <a><strong>{{business.profile}}</strong></a>{{business.profile.phone_number}}</p>
  
        <a class="btn btn-success">Read more</a>
  
      </div>
      <!-- Grid column -->
  
    </div>
    <!-- Grid row -->
  
  </div>
  <!-- News jumbotron -->
            <!-- <div class="jumbotron">
            <p>{{business.profile}}</p>
                <p>{{business.profile.phone_number}}</p>
   <p>{{business.name}}</p>
            </div> -->
        </div>
        <div class="col-md-2"></div>
    </div>
    {%empty%}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h3>its empty here no business available create one</h3>
        </div>
    </div>
    {%endfor%}
</div>
{%endblock%}

hood/templates/footer.html
<!--Footer-->
<footer class="page-footer text-center font-small info-color">

  <div class="rgba-stylish-strong">

    <!--Call to action-->
    <div class="pt-4">
      <a class="btn btn-outline-white"
        href="https://mdbootstrap.com/docs/jquery/getting-started/download/" target="_blank" role="button">subscribe
        <i class="fas fa-bell"></i>
      </a>
    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </div>

</footer>
<!--Footer-->

hood/templates/home.html
{% extends 'base.html'%}
{%block content%}
<div class="container-fluid">
   <div class="row">
     <div class="col-md-1"></div>
    <div class="col-md-10 text-center mt-5">
      
        
                <h2 class="display-4 text-center">Hood Posts </h2>
            
    </div>
    <div class="col-md-1"></div>
  </div>
</div>
<div class="container-fluid mt-5 two">
    {% for post in object_list %}
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">

  <!--Section: Content-->
  <section class="dark-grey-text">

    <!-- Section heading -->

<!--    &lt;!&ndash; Section description &ndash;&gt;-->
<!--    <p class="text-center mx-auto w-responsive mb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit, error amet numquam iure provident voluptate esse quasi, veritatis totam voluptas nostrum quisquam eum porro a pariatur veniam.</p>-->

  	<!-- Grid row -->
    <div class="row align-items-center">

      <!-- Grid column -->
      <div class="col-lg-5 col-xl-4">

        <!-- Featured image -->

        <div class="view overlay rounded z-depth-half ">
          <img class="img-fluid  picp " src="{{post.picture.url}}" alt="Sample image">
          <a>
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-lg-7 col-xl-8">

        <!-- Post title -->
        <h4 class="font-weight-bold mb-3"><a href="{% url 'hood:post-detail' post.id %}" style="color:black"><strong>{{post.title}}</strong></a></h4>
        <!-- Excerpt -->
        <p class="dark-grey-text"style="color:white;">{{post.content}}.</p>
        <!-- Post data -->
        <p>by <a class="font-weight-bold">{{post.profile}}</a>&nbsp;&nbsp;{{post.pub_date|timesince}} AGO</p>
        <!-- Read more button -->
        <a class="btn btn-primary btn-md mx-0 btn-rounded">Read more</a>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

    <hr class="my-1">

  </section>
  <!--Section: Content-->

        </div>
<div class="col-md-1"></div>
    </div>
    {% empty %}
    <!--empty section visible while there are no posts-->
    <div class="row">
            <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <!-- Jumbotron -->
        <div class="jumbotron text-center">

  <!-- Title -->
        <h4 class="card-title h4 pb-2"><strong>No posts yet Sing Up and Share</strong></h4>

  <!-- Card image -->
        <div class="view overlay my-4">
             <img src="https://mdbootstrap.com/img/Photos/Slides/img%20(70).jpg" class="img-fluid" alt="">
            <a href="#">
                <div class="mask rgba-white-slight"></div>
            </a>
        </div>

        <h5 class="indigo-text h5 mb-4">Hood status</h5>

        <p class="card-text">keep informed the people of your hood.</p>

  <!-- Linkedin -->
        <a class="fa-lg p-2 m-2 li-ic"><i class="fab fa-linkedin-in grey-text"></i></a>
  <!-- Twitter -->
        <a class="fa-lg p-2 m-2 tw-ic"><i class="fab fa-twitter grey-text"></i></a>
  <!-- Dribbble -->
        <a class="fa-lg p-2 m-2 fb-ic"><i class="fab fa-facebook-f grey-text"></i></a>

        </div>
<!-- Jumbotron -->
            </div>
            <div class="col-md-2"></div>
            </div>
            </div>
    {%endfor%}
</div>
{%endblock%}

hood/templates/navbar.html
<!--Navbar -->
<nav class="mb-1 navbar navbar-expand-lg navbar-dark info-color">
  <a class="navbar-brand" href="{%url 'hood:home'%}"><strong>My Hood</strong></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-4"
    aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> &nbsp;&nbsp;&nbsp;
  <!--SEARCH FORM-->
    <form class="form-inline ml-auto form" >
    <input class="form-control" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-white btn-md my-2 my-sm-0 ml-3" type="submit">Search</button>
    </form>
  <!--END FORM-->
      {% if user.is_authenticated %}
  <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-4" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user"></i> </a>
        <div class="dropdown-menu dropdown-menu-right dropdown-info" aria-labelledby="navbarDropdownMenuLink-4">
          <a class="dropdown-item" href="{%url 'hood:profile'%}">My account</a>
          <a class="dropdown-item" href="{%url 'logout'%}">Log out</a>
           <a class="dropdown-item" href="{%url 'hood:new_post'%}">Create post</a>
          <a class="dropdown-item" href="{%url 'hood:business'%}">Businesses</a>

        </div>
      </li>
      {%else%}
       <li class="nav-item" style="list-style:none;">
        <a class="nav-link" href="{%url 'login'%}" style="color:white">
          <i class="fas fa-sign-in-alt"></i>Log in </a>
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item" style="list-style:none;">
        <a class="nav-link" href="{%url 'registration'%}" style="color:white">
          <i class="fas fa-user-plus"></i> Sign In</a>
      </li>
      {%endif%}
    </ul>
  </div>
</nav>
<!--/.Navbar -->

<!--<nav class="navbar navbar-dark default-color">-->
<!--  <form class="form-inline my-2  ml-auto">-->
<!--    <input class="form-control" type="search" placeholder="Search" aria-label="Search">-->
<!--    <button class="btn btn-outline-white btn-md my-2 my-sm-0 ml-3" type="submit">Search</button>-->
<!--  </form>-->
<!--</nav>-->

hood/templates/new_business.html
{%extends 'base.html'%}
{%load crispy_forms_tags %}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <!-- Card -->
    <div class="card mx-xl-5 post">

  <!-- Card body -->
    <div class="card-body ">
                 <p class="h4 text-center py-4">Share Business</p>

       <form action="" method="post" enctype="multipart/form-data" class="grey-text font-weight-light">
                {% csrf_token %}
                {{ form|crispy }}
         <div class="form-group text-center py-4 mt-3">
        <button class="btn btn-cyan" type="submit">Post
        </button>
      </div>
         </form>
     </div>
  <!-- Card body -->
</div>
<!-- Card -->
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{%endblock%}

hood/templates/new_post.html
{%extends 'base.html'%}
{%load crispy_forms_tags %}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <!-- Card -->
    <div class="card mx-xl-5 post">

  <!-- Card body -->
    <div class="card-body ">
                 <p class="h4 text-center py-4">Create Post</p>

       <form action="" method="post" enctype="multipart/form-data" class="grey-text font-weight-light">
                {% csrf_token %}
                {{ form|crispy }}
         <div class="form-group text-center py-4 mt-3">
        <button class="btn btn-cyan" type="submit">Post
        </button>
      </div>
         </form>
     </div>
  <!-- Card body -->
</div>
<!-- Card -->
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{%endblock%}

hood/templates/post-detail.html
{%extends 'base.html'%}
{%block content%}

<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <h3>{{post.title}}</h3>
            <p>{{post.content}}</p>
            <p>{{post.neighborhood.name}}</p>
        </div>
    </div>
</div>
{%endblock%}

hood/templates/profile.html
{% extends 'base.html'%}
{%load static%}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 one">
                <div class="card testimonial-card profile one">

  <!-- Background color -->
  <div class="card-up indigo lighten-1"></div>

  <!-- Avatar -->

  <div class="avatar mx-auto white mt-3">
       {%if user.profile%}
   <img src="{{user.profile.profile_pic.url}}"  alt="profile pic" class="rounded-circle" >
      {%else%}
      <img src="{%static 'images/kent.jpg'%}" class="rounded-circle" alt="profile pic">
      {%endif%}
  </div>

<hr>
  <!-- Content -->
  <div class="card-body">
    <!-- Name -->
    <h4 class="card-title">{{user.username}}</h4>
       <p class="card-title colo text-muted font-weight-light">{{user.email}}</p>
      <p class="card-title colo text-muted font-weight-light">{{user.profile.phone_number}}</p>
    <hr>
    <!-- Quotation -->
    <p >Bio: &nbsp; {{user.profile.bio}}
    </p>
      <a href="{%url 'hood:update_profile' user.profile.pk %}"><button type="button" class="btn btn-success" style="float:right">Update Profile</button>
</a>
  </div>

</div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

{%endblock%}

hood/templates/update_profile.html
{%extends 'base.html'%}
{%load crispy_forms_tags %}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <!-- Card -->
    <div class="card mx-xl-5 post">

  <!-- Card body -->
    <div class="card-body ">
                 <p class="h4 text-center py-4">Update Profile</p>

       <form action="" method="post" enctype="multipart/form-data" class="grey-text font-weight-light">
                {% csrf_token %}
                {{ form|crispy }}
         <div class="form-group text-center py-4 mt-3">
        <button class="btn btn-cyan" type="submit">Update
        </button>
      </div>
         </form>
     </div>
  <!-- Card body -->
</div>
<!-- Card -->
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{%endblock%}

users/templates/registration.html
{% extends 'base.html'%}
{%load crispy_forms_tags %}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="card mx-xl-5 post">

  <!-- Card body -->
    <div class="card-body ">
                 <p class="h4 text-center py-4">Join Today</p>

       <form action="" method="post" class="grey-text font-weight-light">
                {% csrf_token %}
                {{ form|crispy }}
         <div class="form-group text-center py-4 mt-3">
        <button class="btn btn-cyan" type="submit">Register
        </button>
      </div>
         </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an account? <a class="ml-2" href=""> Log In</a>
            </small>
        </div>
     </div>
  <!-- Card body -->
</div>
         </form>
            <!--end form-->
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock content%}